parsers:
  - crowdsecurity/syslog-logs
  - parsers/s01-parse/Railline/axigen-logs.yaml
  - crowdsecurity/dateparse-enrich
scenarios:
  - scenarios/Railline/axigen-tls-probing.yaml
postoverflows:
  - ""
log_file: axigen-tls-probing.log
log_type: axigen
ignore_parsers: true
