parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/postfix-logs
  - crowdsecurity/dateparse-enrich
scenarios:
  - melite/postfix-very-slow-bf
log_file: postfix-very-slow-bf.log
log_type: syslog
ignore_parsers: true
