parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/crowdsecurity/pgsql-logs.yaml
scenarios:
- ""
postoverflows:
- ""
log_file: pgbouncer-logs.log
log_type: pgbouncer
labels: {}
ignore_parsers: false
override_statics: []
