parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/sshd-logs
  - crowdsecurity/dateparse-enrich
scenarios:
  - melite/ssh-ultra-slow-bf
log_file: ssh-ultra-slow-bf.log
log_type: syslog
ignore_parsers: true
