parsers:
  - crowdsecurity/syslog-logs
  - ./parsers/s01-parse/PumbaLP/cowrie-json-logs.yaml
  - crowdsecurity/dateparse-enrich
scenarios:
  - crowdsecurity/ssh-bf
postoverflows: []
log_file: cowrie-json-ssh-bf.log
log_type: cowrie
ignore_parsers: true
