parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/nikita-popov/radicale-logs.yaml
scenarios:
- ./scenarios/nikita-popov/radicale-bf.yaml
- ./scenarios/nikita-popov/radicale-scan.yaml
postoverflows:
- ""
log_file: radicale-logs.log
log_type: radicale
