parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/dovecot-logs
  - crowdsecurity/dateparse-enrich
scenarios:
  - melite/dovecot-very-slow-bf
log_file: dovecot-very-slow-bf.log
log_type: syslog
ignore_parsers: true
