parsers:
  - crowdsecurity/syslog-logs
  - ./parsers/s01-parse/ksi-digital/cowrie-json-logs.yaml
  - crowdsecurity/dateparse-enrich
scenarios:
  - crowdsecurity/telnet-bf
postoverflows: []
log_file: cowrie-json-telnet-bf.log
log_type: cowrie
ignore_parsers: true
