parsers:
- crowdsecurity/postfix-logs
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- scenarios/Guezli/postfix-honeypot-users.yaml
postoverflows:
- ""
log_file: postfix-honeypot-users.log
log_type: syslog
ignore_parsers: true
