parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- crowdsecurity/aws-cloudtrail
scenarios:
- crowdsecurity/aws-cis-benchmark-root-usage
postoverflows:
- ""
log_file: aws-cis-benchmark-root-usage.log
log_type: aws-cloudtrail
labels: {}
ignore_parsers: true
override_statics: []
