parsers:
- ./parsers/s00-raw/crowdsecurity/cef-logs.yaml
- ./parsers/s01-parse/jacob-masse/flowtriq-logs.yaml
scenarios:
- ./scenarios/jacob-masse/flowtriq-ddos-attack.yaml
postoverflows:
- ""
log_file: flowtriq-logs.log
log_type: cef
