parsers:
    - crowdsecurity/syslog-logs
    - crowdsecurity/dateparse-enrich
    - ./parsers/s01-parse/LazarisIRL/romm-logs.yaml
scenarios:
    - ./scenarios/LazarisIRL/romm-bf.yaml
postoverflows:
    - ""
log_file: romm-bf.log
log_type: romm
