parsers:
    - crowdsecurity/syslog-logs
    - crowdsecurity/dateparse-enrich
    - ./parsers/s01-parse/LazarisIRL/romm-logs.yaml
scenarios:
postoverflows:
    - ""
log_file: romm-logs.log
log_type: romm
