parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- crowdsecurity/aws-cloudtrail
scenarios:
- crowdsecurity/aws-cis-benchmark-s3-policy-change
postoverflows:
- ""
log_file: aws-cis-benchmark-s3-policy-change.log
log_type: aws-cloudtrail
labels: {}
ignore_parsers: true
override_statics: []
