parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/postfix-logs
  - crowdsecurity/dateparse-enrich
  - melite/postfix-submission-auth
scenarios:
  - melite/postfix-submission-very-slow-bf
log_file: postfix-submission-very-slow-bf.log
log_type: syslog
ignore_parsers: true
