parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/postfix-logs
  - crowdsecurity/dateparse-enrich
  - melite/postfix-submission-auth
scenarios:
  []
log_file: postfix-submission-auth.log
log_type: syslog
ignore_parsers: true
