parsers:
  - crowdsecurity/syslog-logs
  - crowdsecurity/dovecot-logs
  - crowdsecurity/dateparse-enrich
scenarios:
  - scenarios/melite/dovecot-time-based-bf.yaml
log_file: dovecot-time-based-bf.log
log_type: syslog
