parsers:
  - ./parsers/s01-parse/PumbaLP/adguardhome-dot-errors.yaml
scenarios:
  - ./scenarios/PumbaLP/adguardhome-dot-scan.yaml
postoverflows: []
log_file: adguardhome-dot-scan.log
log_type: adguardhome
