name: crowdsecurity/supabase-compose
collections:
  - crowdsecurity/nginx
parsers:
  - crowdsecurity/supabase-docker-pgsql
scenarios:
  - crowdsecurity/pgsql-bf
  - crowdsecurity/pgsql-user-enum

description: "supabase docker compose support"
labels:
  label: "Supabase - Generic Protection"
author: crowdsecurity
tags:
  - security_engine
  - linux
  - pgsql
  - postgres
  - bruteforce
  - nginx
  - supabase
  - docker-compose
  - docker
