parsers:
  - crowdsecurity/syslog-logs
  - ./parsers/s01-parse/proonoob/openvpn.yaml
scenarios:
  - ./scenarios/proonoob/openvpn-bf.yaml
postoverflows:
  - ""
log_file: openvpn-logs.log
log_type: syslog
