parsers:
  - crowdsecurity/syslog-logs
  - ./parsers/s01-parse/PumbaLP/cowrie-json-logs.yaml
  - crowdsecurity/dateparse-enrich
scenarios:
  - ./scenarios/PumbaLP/cowrie-precision.yaml
postoverflows: []
log_file: cowrie-precision.log
log_type: cowrie
ignore_parsers: true
