parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- crowdsecurity/aws-cloudtrail
scenarios:
- crowdsecurity/aws-cis-benchmark-console-auth-fail
postoverflows:
- ""
log_file: aws-cis-benchmark-console-auth-fail.log
log_type: aws-cloudtrail
labels: {}
ignore_parsers: true
override_statics: []
