parsers:
- crowdsecurity/postfix-logs
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- scenarios/Guezli/postfix-sasl-bf.yaml
postoverflows:
- ""
log_file: postfix-sasl-bf.log
log_type: syslog
ignore_parsers: true
