parsers:
- crowdsecurity/postfix-logs
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- Guezli/postfix-sasl-bf
postoverflows:
- ""
log_file: postfix-sasl-bf.log
log_type: syslog
ignore_parsers: true
