parsers:
- parsers/s01-parse/Guezli/mailcow-f2b-bans.yaml
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- scenarios/Guezli/mailcow-f2b-feed.yaml
postoverflows:
- ""
log_file: mailcow-f2b-feed-auto.log
log_type: mailcow-f2b
