parsers:
  - crowdsecurity/syslog-logs
  - melite/sshd-preauth-disconnect
  - crowdsecurity/dateparse-enrich
scenarios:
  []
log_file: sshd-preauth-disconnect.log
log_type: syslog
ignore_parsers: true
