name: Lint Index

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'appsec-configs/**.md'
      - 'appsec-configs/**.yaml'
      - 'appsec-configs/**.yml'
      - 'appsec-rules/**.md'
      - 'appsec-rules/**.yaml'
      - 'appsec-rules/**.yml'
      - 'collections/**.md'
      - 'collections/**.yaml'
      - 'collections/**.yml'
      - 'contexts/**.md'
      - 'contexts/**.yaml'
      - 'contexts/**.yml'
      - 'parsers/**.md'
      - 'parsers/**.yaml'
      - 'parsers/**.yml'
      - 'postoverflows/**.md'
      - 'postoverflows/**.yaml'
      - 'postoverflows/**.yml'
      - 'scenarios/**.md'
      - 'scenarios/**.yaml'
      - 'scenarios/**.yml'
      - '.github/workflows/lint-index.yml'
      - "src/**"
      - "pyproject.toml"
      - "uv.lock"
  push:
    paths:
      - 'appsec-configs/**.md'
      - 'appsec-configs/**.yaml'
      - 'appsec-configs/**.yml'
      - 'appsec-rules/**.md'
      - 'appsec-rules/**.yaml'
      - 'appsec-rules/**.yml'
      - 'collections/**.md'
      - 'collections/**.yaml'
      - 'collections/**.yml'
      - 'contexts/**.md'
      - 'contexts/**.yaml'
      - 'contexts/**.yml'
      - 'parsers/**.md'
      - 'parsers/**.yaml'
      - 'parsers/**.yml'
      - 'postoverflows/**.md'
      - 'postoverflows/**.yaml'
      - 'postoverflows/**.yml'
      - 'scenarios/**.md'
      - 'scenarios/**.yaml'
      - 'scenarios/**.yml'
      - '.github/workflows/lint-index.yml'
      - "src/**"
      - "pyproject.toml"
      - "uv.lock"

permissions:
  contents: read

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          version: 0.5.24
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: set up python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: ".python-version"

      - name: run hublint on new index
        run: |
          uv sync --all-extras --dev --locked
          uv run mkindex
          uv run hublint defaults > .hublint.toml
          uv run hublint check --color always --no-warning-details
